import type { Metadata } from "next";
import { Nav } from "@/components/layout/Nav";
import { Footer } from "@/components/layout/Footer";
import { FadeIn } from "@/components/ui/fade-in";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Meridian AI privacy policy — how we collect, use, and protect your data. GDPR and CCPA compliant.",
  alternates: { canonical: "https://meridian.ai/privacy" },
};

const EFFECTIVE_DATE = "April 1, 2026";
const LAST_UPDATED = "April 1, 2026";

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main id="main-content">
        <section className="py-32 border-b border-[#3F3F46]/50">
          <div className="max-w-6xl mx-auto px-6">
            <FadeIn>
              <p className="text-xs font-medium tracking-widest uppercase text-[#14B8A6] mb-6">
                Legal
              </p>
              <h1
                className="text-5xl sm:text-6xl font-bold text-[#FAFAFA] mb-6"
                style={{ textWrap: "balance" } as React.CSSProperties}
              >
                Privacy Policy
              </h1>
              <p className="text-sm text-[#71717A]">
                Effective: {EFFECTIVE_DATE} · Last updated: {LAST_UPDATED}
              </p>
            </FadeIn>
          </div>
        </section>

        <section className="py-24">
          <div className="max-w-6xl mx-auto px-6">
            <div className="grid grid-cols-1 lg:grid-cols-[260px_1fr] gap-16 items-start">
              {/* Sticky TOC */}
              <FadeIn>
                <nav
                  className="lg:sticky lg:top-24 rounded-xl border border-[#3F3F46]/60 bg-[#18181B] p-6"
                  aria-label="Page sections"
                >
                  <p className="text-xs font-medium tracking-widest uppercase text-[#52525B] mb-4">
                    Contents
                  </p>
                  <ol className="flex flex-col gap-3 list-none" role="list">
                    {[
                      ["#who-we-are", "Who we are"],
                      ["#what-we-collect", "What we collect"],
                      ["#how-we-use", "How we use it"],
                      ["#sharing", "Sharing"],
                      ["#retention", "Retention"],
                      ["#your-rights", "Your rights"],
                      ["#cookies", "Cookies"],
                      ["#security", "Security"],
                      ["#changes", "Changes"],
                      ["#contact", "Contact us"],
                    ].map(([href, label]) => (
                      <li key={href}>
                        <a
                          href={href}
                          className="text-sm text-[#71717A] hover:text-[#A1A1AA] transition-colors"
                        >
                          {label}
                        </a>
                      </li>
                    ))}
                  </ol>
                </nav>
              </FadeIn>

              {/* Policy content */}
              <FadeIn delay={0.1}>
                <div className="flex flex-col gap-16 text-[#A1A1AA] leading-relaxed">
                  <PolicySection id="who-we-are" heading="Who we are">
                    <p>
                      Meridian AI, Inc. ("Meridian", "we", "us") is a Delaware corporation
                      headquartered at 548 Market Street, San Francisco, CA 94104. We provide
                      evaluation, observability, and deployment infrastructure for AI systems.
                    </p>
                    <p>
                      Questions about this policy can be directed to{" "}
                      <a
                        href="mailto:privacy@meridian.ai"
                        className="text-[#14B8A6] hover:text-[#2DD4BF] transition-colors"
                      >
                        privacy@meridian.ai
                      </a>
                      .
                    </p>
                  </PolicySection>

                  <PolicySection id="what-we-collect" heading="What we collect">
                    <p>We collect information you give us directly and information generated by your use of Meridian.</p>
                    <SubHeading>Account information</SubHeading>
                    <p>
                      Name, work email address, company name, and job title when you create an
                      account. Payment information is collected by Stripe and is not stored on
                      Meridian servers.
                    </p>
                    <SubHeading>Usage data</SubHeading>
                    <p>
                      Evaluation runs, model configurations, API call logs, and dashboard
                      interactions. This data is used to operate the service and is not used for
                      advertising.
                    </p>
                    <SubHeading>Technical data</SubHeading>
                    <p>
                      IP addresses, browser type, operating system, and referring URLs collected
                      automatically when you access Meridian. We use this data to detect abuse and
                      maintain service reliability.
                    </p>
                    <SubHeading>Communications</SubHeading>
                    <p>
                      When you contact us by email or via our support channels, we retain those
                      communications to resolve your request and improve our service.
                    </p>
                  </PolicySection>

                  <PolicySection id="how-we-use" heading="How we use it">
                    <p>We use the data we collect to:</p>
                    <ul className="flex flex-col gap-2 list-none ml-0">
                      {[
                        "Operate and improve the Meridian platform",
                        "Authenticate users and enforce access controls",
                        "Send transactional emails (invoices, alerts, critical notices)",
                        "Detect fraud, abuse, and security incidents",
                        "Comply with legal obligations",
                        "Respond to support requests",
                      ].map((item) => (
                        <li key={item} className="flex items-start gap-2 text-sm">
                          <span className="text-[#14B8A6] mt-0.5 shrink-0" aria-hidden="true">→</span>
                          {item}
                        </li>
                      ))}
                    </ul>
                    <p>
                      We do not sell your personal data. We do not use your data to train AI models.
                      We do not send marketing emails without explicit opt-in.
                    </p>
                  </PolicySection>

                  <PolicySection id="sharing" heading="Sharing">
                    <p>
                      We share data only in the following circumstances:
                    </p>
                    <SubHeading>Service providers</SubHeading>
                    <p>
                      We use sub-processors to operate Meridian — cloud infrastructure (AWS), payment
                      processing (Stripe), error monitoring (Sentry), and customer support
                      (Intercom). Each sub-processor is contractually bound to handle data only as
                      directed by us. Our current sub-processor list is available on request.
                    </p>
                    <SubHeading>Legal requirements</SubHeading>
                    <p>
                      We may disclose data if required by law, court order, or to protect the
                      rights, property, or safety of Meridian, our customers, or others. We will
                      notify affected customers when legally permitted to do so.
                    </p>
                    <SubHeading>Business transfers</SubHeading>
                    <p>
                      In the event of a merger, acquisition, or asset sale, customer data may
                      transfer to the acquiring party. We will notify customers of any such change
                      and the acquiring party will be bound by this policy.
                    </p>
                  </PolicySection>

                  <PolicySection id="retention" heading="Retention">
                    <p>
                      Account data is retained for the life of your account plus 90 days after
                      deletion to allow for dispute resolution. Usage logs are retained for 12 months.
                      Evaluation run data is retained until you delete it or close your account.
                    </p>
                    <p>
                      You can request deletion of your account and associated data at any time by
                      emailing{" "}
                      <a
                        href="mailto:privacy@meridian.ai"
                        className="text-[#14B8A6] hover:text-[#2DD4BF] transition-colors"
                      >
                        privacy@meridian.ai
                      </a>
                      . We will process deletion requests within 30 days.
                    </p>
                  </PolicySection>

                  <PolicySection id="your-rights" heading="Your rights">
                    <p>
                      Depending on your location, you may have the following rights under GDPR
                      (EEA/UK residents) or CCPA (California residents):
                    </p>
                    <ul className="flex flex-col gap-3 list-none ml-0">
                      {[
                        ["Access", "Request a copy of the personal data we hold about you."],
                        ["Correction", "Request correction of inaccurate or incomplete data."],
                        ["Deletion", "Request deletion of your personal data, subject to legal retention requirements."],
                        ["Portability", "Request your data in a structured, machine-readable format."],
                        ["Objection", "Object to processing of your data for direct marketing or on grounds of legitimate interest."],
                        ["Restriction", "Request that we restrict processing of your data in certain circumstances."],
                        ["Opt-out of sale", "California residents: we do not sell personal data, but you may submit a request to confirm this."],
                      ].map(([right, desc]) => (
                        <li key={right} className="flex items-start gap-3">
                          <span className="text-[#FAFAFA] font-medium text-sm shrink-0 w-28">{right}</span>
                          <span className="text-sm">{desc}</span>
                        </li>
                      ))}
                    </ul>
                    <p>
                      To exercise any of these rights, email{" "}
                      <a
                        href="mailto:privacy@meridian.ai"
                        className="text-[#14B8A6] hover:text-[#2DD4BF] transition-colors"
                      >
                        privacy@meridian.ai
                      </a>{" "}
                      with your request. We will respond within 30 days. We may ask you to verify
                      your identity before processing the request.
                    </p>
                  </PolicySection>

                  <PolicySection id="cookies" heading="Cookies">
                    <p>
                      Meridian uses a small number of cookies strictly necessary to operate the
                      service. We do not use advertising cookies or third-party tracking cookies.
                    </p>
                    <div className="rounded-xl border border-[#3F3F46]/60 bg-[#18181B] overflow-hidden mt-2">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="border-b border-[#3F3F46]/60">
                            <th className="text-left p-4 text-[#FAFAFA] font-medium">Cookie</th>
                            <th className="text-left p-4 text-[#FAFAFA] font-medium">Purpose</th>
                            <th className="text-left p-4 text-[#FAFAFA] font-medium">Duration</th>
                          </tr>
                        </thead>
                        <tbody>
                          {[
                            ["meridian_session", "Authenticates your session", "Session"],
                            ["meridian_csrf", "Prevents cross-site request forgery", "Session"],
                            ["meridian_prefs", "Stores UI preferences (theme, layout)", "1 year"],
                          ].map(([name, purpose, duration]) => (
                            <tr key={name} className="border-b border-[#3F3F46]/40 last:border-0">
                              <td className="p-4 font-mono text-xs text-[#14B8A6]">{name}</td>
                              <td className="p-4 text-[#A1A1AA]">{purpose}</td>
                              <td className="p-4 text-[#71717A]">{duration}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </PolicySection>

                  <PolicySection id="security" heading="Security">
                    <p>
                      We use industry-standard security measures to protect your data, including
                      TLS 1.2+ in transit, AES-256 at rest, and access controls limiting employee
                      access to customer data on a need-to-know basis.
                    </p>
                    <p>
                      For a full description of our security posture, see our{" "}
                      <a
                        href="/security"
                        className="text-[#14B8A6] hover:text-[#2DD4BF] transition-colors"
                      >
                        security page
                      </a>
                      .
                    </p>
                  </PolicySection>

                  <PolicySection id="changes" heading="Changes to this policy">
                    <p>
                      We will notify you of material changes to this policy by email or by
                      displaying a prominent notice in the Meridian dashboard at least 30 days
                      before the change takes effect. The "last updated" date at the top of this
                      page reflects the most recent revision.
                    </p>
                    <p>
                      Continued use of Meridian after a change takes effect constitutes acceptance
                      of the revised policy.
                    </p>
                  </PolicySection>

                  <PolicySection id="contact" heading="Contact us">
                    <p>
                      For privacy questions, data subject requests, or to reach our Data Protection
                      Officer:
                    </p>
                    <address className="not-italic rounded-xl border border-[#3F3F46]/60 bg-[#18181B] p-6 flex flex-col gap-2 text-sm mt-2">
                      <p className="text-[#FAFAFA] font-medium">Meridian AI, Inc.</p>
                      <p>548 Market Street, San Francisco, CA 94104</p>
                      <a
                        href="mailto:privacy@meridian.ai"
                        className="text-[#14B8A6] hover:text-[#2DD4BF] transition-colors"
                      >
                        privacy@meridian.ai
                      </a>
                    </address>
                  </PolicySection>
                </div>
              </FadeIn>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

function PolicySection({
  id,
  heading,
  children,
}: {
  id: string;
  heading: string;
  children: React.ReactNode;
}) {
  return (
    <div id={id} className="flex flex-col gap-5 scroll-mt-24">
      <h2 className="text-2xl font-semibold text-[#FAFAFA]">{heading}</h2>
      {children}
    </div>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <h3 className="text-base font-semibold text-[#FAFAFA] mt-2">{children}</h3>;
}
